
// src/lib/shareText.ts
export const getRandomShareText = (): string => {
  const shareTexts = [
    "@blocksky.app just made my Bluesky experience better! ✨",
    "Tired of clutter? @blocksky.app helps you curate your space. 🛡️",
    "Curate your Bluesky like never before with @blocksky.app! 🚀",
    "Mass block accounts with ease using @blocksky.app. Try it now! 🧹",
    "Safer social spaces start with @blocksky.app. 🌈",
    "Discover the magic of curated feeds on Bluesky with @blocksky.app! ✨",
    "@blocksky.app: your best friend for managing your Bluesky. 🤝",
    "Simplify your Bluesky with @blocksky.app. 🎶",
    "Personalize your Bluesky like a pro with @blocksky.app! 💼",
    "Effortless account management starts with @blocksky.app! 👋",
    "My Bluesky feels more personalized thanks to @blocksky.app! 🌟",
    "Transform your social experience with @blocksky.app! 🚀",
    "@blocksky.app is Bluesky's perfect companion. 🌈",
    "Create a Bluesky space you love with @blocksky.app. 💙",
    "@blocksky.app: the tool you didn't know you needed. 🌟",
    "Control your Bluesky experience with @blocksky.app. 🛡️",
    "Your Bluesky, your rules—powered by @blocksky.app! ✨",
    "@blocksky.app makes Bluesky even better. 🚀",
    "Mass blocking, simplified by @blocksky.app! 👌",
    "Your curated Bluesky experience starts here—@blocksky.app! 🌟",
    "Make your Bluesky safe and personalized with @blocksky.app. 🌈",
    "@blocksky.app empowers you to take control of your Bluesky. 🛡️",
    "Curate your Bluesky timeline with @blocksky.app's easy tools. 🔧",
    "@blocksky.app helps you manage your Bluesky effortlessly. 🤝",
    "Your dream Bluesky feed is just a click away with @blocksky.app! ✨",
    "@blocksky.app is the ultimate curation tool for Bluesky users. 🚀",
    "Transform your social interactions with @blocksky.app's features. 🌟",
    "Say goodbye to chaos—hello to @blocksky.app! 🧹",
    "Your Bluesky, your way—thanks to @blocksky.app. 🌈",
    "Take control of your Bluesky feed today with @blocksky.app! 🛡️",
    "Mass blocking has never been this easy—@blocksky.app is here! 👋",
    "Make Bluesky your happy place with @blocksky.app. 🌟",
    "Curate your Bluesky effortlessly with @blocksky.app. 🚀",
    "@blocksky.app: the smart way to manage your social space. 🧠",
    "@blocksky.app helps you personalize and protect your Bluesky. 🛡️",
    "Take charge of your Bluesky interactions with @blocksky.app. 🤝",
    "Safer Bluesky starts with smarter tools like @blocksky.app. 🌈",
    "Curated social spaces are the future—start with @blocksky.app. 🚀",
    "Simplify your Bluesky with @blocksky.app's powerful tools. 🌟",
    "@blocksky.app makes managing Bluesky effortless and fun. ✨",
    "Keep your Bluesky space yours with @blocksky.app! 💙",
    "Bluesky just got better with @blocksky.app! 🛡️",
    "Enjoy your Bluesky your way—thanks to @blocksky.app. 🌈",
    "Mass block in seconds with @blocksky.app. 🔧",
    "The easiest way to manage Bluesky? It's @blocksky.app! 🚀",
    "Revolutionize your Bluesky with @blocksky.app's features. 🌟",
    "Bluesky feels like home with @blocksky.app. 🏠",
    "@blocksky.app: helping you create a safer social space. 🛡️",
    "Your Bluesky, curated perfectly with @blocksky.app. 🌈",
    "@blocksky.app makes mass blocking a breeze. 👋",
    "Keep unwanted content out with @blocksky.app! 🚀",
    "Bluesky just got easier—@blocksky.app's got your back. 🌟",
    "Curated timelines, happier days—try @blocksky.app! ✨",
    "@blocksky.app: the ultimate Bluesky curation tool. 🛡️",
    "Safer social spaces? @blocksky.app's here for you. 🌈",
    "Bluesky, simplified by @blocksky.app. 🚀",
    "Your Bluesky feed, your rules—@blocksky.app delivers. 🌟",
    "Manage Bluesky like a pro with @blocksky.app. 💼",
    "Your Bluesky, your way—powered by @blocksky.app. 🚀",
    "@blocksky.app: where personalization meets protection. 🛡️",
    "Create a timeline you love with @blocksky.app! 🌈",
    "Bluesky is better when it's curated—thanks to @blocksky.app. 🌟",
    "Effortless feed management starts with @blocksky.app! 🚀",
    "Mass block accounts in seconds with @blocksky.app! 👌",
    "Take back control of Bluesky with @blocksky.app's features. 🛡️",
    "@blocksky.app helps you build your ideal Bluesky. 🌟",
    "Say hello to curated timelines—@blocksky.app makes it happen. 🌈",
    "Make Bluesky yours with @blocksky.app's powerful tools. 🚀",
    "Enjoy safer interactions with @blocksky.app's smart tools. 🛡️",
    "Transform Bluesky with the power of @blocksky.app! 🌟",
    "Simplify your timeline with @blocksky.app's features. ✨",
    "Your curated social space starts here—@blocksky.app! 🚀",
    "Bluesky made better: @blocksky.app helps you manage it all. 🌈",
    "Control your feed, your way—@blocksky.app makes it easy. 🛡️",
    "Bluesky just got simpler with @blocksky.app! 👌",
    "Your safer social space is just a click away—@blocksky.app. 🌟",
    "Curate your timeline like a pro—@blocksky.app's here to help. 🚀",
    "Mass blocking has never been simpler—@blocksky.app delivers. 🛡️",
    "Your Bluesky, your sanctuary—thanks to @blocksky.app. 🌈",
    "@blocksky.app: revolutionizing social feed management. 🚀",
    "Keep your Bluesky space as you like it with @blocksky.app. 🌟",
    "Bluesky management made easy—@blocksky.app's got you covered. ✨",
    "Personalize your Bluesky with @blocksky.app's unique tools. 🚀",
    "Create a curated timeline with @blocksky.app's features. 🛡️",
    "Transform Bluesky with the power of @blocksky.app. 🌟",
    "Mass blocking, simplified by @blocksky.app's smart tools. 🌈",
    "Say goodbye to chaos—hello, curated timelines with @blocksky.app! 🚀",
    "Your social feed, your way—start with @blocksky.app! 🛡️",
    ];
  return shareTexts[Math.floor(Math.random() * shareTexts.length)];
};